graph LR
  GC["Game Client<br/>[HTML, JavaScript]<br/>(Browser)"]
  subgraph "Phaser Multiplayer Spike Infrastructure"
    WA["Websocket API<br/>[Lambda Proxy Integration]<br/>(API Gateway v2)"]
    RH["Route Handler<br/>[NodeJS]<br/>(Lambda)"]
    CT["Connections Table<br/>(DynamoDB)"]
  end
  GC --socket--> WA --routes--> RH --read/write--> CT