graph LR
  GC["Game Client (Browser)"]
  subgraph "Phaser Multiplayer Spike Infrastructure"
    WA["Websocket API (API Gateway v2)"]
    RH["Route Handler (Lambda)"]
    CT["Connections Table (DynamoDB)"]
  end
  GC--socket-->WA--routes-->RH--read/write-->CT