sequenceDiagram
  participant GC as Game Client
  participant WA as Websocket API
  participant RH as Route Handler
  participant CT as Connections Table

  GC->>WA: send current_connections action
  WA->>RH: route to current_connections<br />route handler
  RH->>CT: get all Connections
  CT->>RH: connections
  RH->>WA: return currentConnectionIds
  WA->>GC: return currentConnectionIds