sequenceDiagram
  participant GC as Game Client
  participant WA as Websocket API
  participant RH as Route Handler
  participant CT as Connections Table

  GC->>WA: send $disconnect action
  WA->>RH: route to disconnect<br />route Handler
  RH->>CT: delete connection
  RH->>CT: get all Connections
  CT->>RH: connections
  RH->>WA: forward disconnection<br />to all connections
  WA->>GC: forward disconnected action