sequenceDiagram
  participant GC as Game Client
  participant WA as Websocket API
  participant RH as Route Handler
  participant CT as Connections Table

  GC->>WA: send movement action
  WA->>RH: route to movement<br />route handler
  RH->>CT: get all Connections
  CT->>RH: connections
  RH->>WA: forward movement<br />to all connections
  WA->>GC: forward movement action